#!/usr/bin/env bash
# /redirect_me is redirecting to another page using nginx
apt-get -y install nginx
service nginx start
sed -i '26 i \        rewrite ^/redirect_me https://www.amazon.com/ permanent;' /etc/nginx/sites-available/default
service nginx restart
