#!/usr/bin/env bash
# /redirect_me is redirecting to another page using nginx
apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo touch /usr/share/nginx/html/redirect_me
sudo sed -i '26 i \        rewrite ^/redirect_me https://www.amazon.com/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
