#!/usr/bin/env bash
# init
case "$1" in
start)
	./manage_my_process &
	echo $$ < /var/run/my_process.pid
	echo "manage_my_process started"
;;
stop)
	kill "$(pgrep -f manage_my_process)"
	rm -f /var/run/my_process.pid
	echo "manage_my_process stopped"
;;
restart)
	$0 stop
	$0 start
        echo "manage_my_process restarted"
;;
*)
	echo "Usage: manage_my_process {start|stop|restart}"
esac