#!/usr/bin/env bash
# creates the file with pid, kills processes
echo $$ > /var/run/holbertonscript.pid
trap "echo Y U no love me?!" SIGINT
trap "rm -f /var/run/holbertonscript.pid; echo I hate the kill command; exit" SIGTERM
while :
do
      echo "To infinity and beyond"
      sleep 3
done
