#!/usr/bin/env bash
# bad luck for the 4th loop iteration, good luck for the 8th, HS for other
i=0
while [ $i -le 10 ]
do
    i=$(( i+1 ))
    if [ $i == 4 ]
    then
        echo "bad luck"
    elif [ $i == 8 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
done
