#!/usr/bin/env bash
# localhost resolves to 127.0.0.2, facebook to 8.8.8.8
sudo cp /etc/hosts ~/hosts.new
sudo sed -i '1 i \127.0.0.2 localhost' ~/hosts.new
sudo sed -i '2 i \8.8.8.8 facebook.com' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
