#!/usr/bin/env bash
# configures Nginx so it runs as nginx user and not root
sed -i 's/80/8080' /etc/nginx/sites-available/default
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
service nginx restart
