#!/usr/bin/env bash
# configures Nginx so it runs as nginx user and not root
pkill -f apache2
service nginx start
sed -i 's/80 default_server/8080 default_server/g' \
    /etc/nginx/sites-available/default
chmod 777 /etc/nginx/nginx.conf
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
service nginx restart
