#!/usr/bin/env bash
# configures Nginx so it runs as nginx user and not root
pkill -f apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 777 /etc/nginx/nginx.conf
sed -i 's/www-data;/nginx;/g' /etc/nginx/nginx.conf
service nginx restart
