#!/usr/bin/env bash
# run nginx as nginx user
sed -i "1 i \ user nginx;" /etc/nginx/nginx.conf | sudo tee
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
su -c "pkill apache2"
su nginx -c "start-stop-daemon --start --pidfile /run/nginx.pid --exec /usr/sbin/nginx" -s /bin/bash
